config/routes.rb
Rails.application.routes.draw do

  resources :servlets, only: [:index,:create]
  resources :images, only: [:index, :destroy] do
    resources :servlets, only: :new
  end

  get '/style_test' => 'application#style_test'
  root to: 'servlets#index'
end

app/models/image.rb
class Image
  attr_accessor :id, :tags, :exposed_ports, :volumes

  def initialize
    self.tags = []
    self.exposed_ports = []
    self.volumes = []
  end

  def self.all
    Docker::Image.all.map { |i| create_from_docker(i) }
  end

  def self.find(id)
    id_string = id.to_s
    image = create_from_docker(Docker::Image.all.select{ |i| i.id == id_string }.first)
    return unless image
    image.update_from_details Docker::Image.get(id_string)
    image
  end

  def self.delete(id)
    image = Docker::Image.get(id.to_s)
    image.remove if image
    true
  end

  def update_from_details(image_data)
    self.exposed_ports = image_data.info['Config']['ExposedPorts'].try(:keys) || []
    self.volumes = image_data.info['Config']['Volumes'].try(:keys) || []
  end

  protected
  def self.create_from_docker(image_data)
    return unless image_data
    image = Image.new
    image.id = image_data.id
    image.tags = image_data.info['RepoTags']
    image
  end

end

app/models/servlet.rb
class Servlet < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :image, presence: true
  serialize :ports, JSON 
  serialize :volumes, JSON
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end

  def destroy
    Image.delete(params['id'])
    redirect_to :back, notice: 'Image deleted!'
  end
end

app/controllers/servlets_controller.rb
class ServletsController < ApplicationController
  def index
    @servlets = Servlet.order(:name).all
  end

  def new
    @image = Image.find(params[:image_id])
    @servlet = Servlet.new
  end

  def create
    @servlet = Servlet.new(params_servlet)
    if @servlet.save
        redirect_to servlets_path
    else
        render :new
    end
  end

private
  def params_servlet
    params.require(:servlet).permit(:name, :image).tap do |wl|
        wl[:ports] = params[:servlet][:ports]
        wl[:volumes] = params[:servlet][:volumes]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/style_test.html.erb
<!-- Sample Content to Plugin to Template -->
<h1>CSS Basic Elements</h1>

<p>
  The purpose of this HTML is to help determine what default settings are with CSS and to make sure that all possible
  HTML Elements are included in this HTML so as to not miss any possible Elements when designing a site.
</p>

<hr/>

<h1 id="headings">Headings</h1>
<h1>Heading 1</h1>
<h2>Heading 2</h2>
<h3>Heading 3</h3>
<h4>Heading 4</h4>
<h5>Heading 5</h5>
<h6>Heading 6</h6>

<h1 id="headings">Inverse Headings</h1>
<h1 class="inverse">Heading 1</h1>
<h2 class="inverse">Heading 2</h2>
<h3 class="inverse">Heading 3</h3>
<h4 class="inverse">Heading 4</h4>
<h5 class="inverse">Heading 5</h5>
<h6 class="inverse">Heading 6</h6>

<hr/>

<h1 id="paragraph">Paragraph</h1>
<img src="/assets/rails.png" alt="CSS | God's Language"/>
<p>
  Lorem ipsum dolor sit amet, <a href="#" title="test link">test link</a> adipiscing elit. Nullam dignissim convallis
  est. Quisque aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet
  at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo,
  eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. Mauris a
  ante. Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.
</p>
<p>
  Lorem ipsum dolor sit amet, <em>emphasis</em> consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque
  aliquam. Donec faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt
  nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat
  enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy. Mauris a ante.
  Suspendisse quam sem, consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus.
</p>

<hr/>

<h1 id="list_types">List Types</h1>
<h3>Definition List</h3>
<dl>
  <dt>Definition Term 1</dt>
  <dd>This is a definition list division.</dd>
  <dt>Definition Term 2</dt>
  <dd>This is a definition list division.</dd>
</dl>

<h3>Ordered List</h3>
<ol>
  <li>List Item 1</li>
  <li>List Item 2</li>
  <li>List Item 3</li>
</ol>

<h3>Unordered List</h3>
<ul>
  <li>List Item 1</li>
  <li>List Item 2</li>
  <li>List Item 3</li>
</ul>

<hr/>
<h1>Button Colors</h1>
<button class="btn btn-default">Default</button>
<button class="btn btn-primary">Primary</button>
<button class="btn btn-warning">Warning</button>
<button class="btn btn-success">Success</button>
<button class="btn btn-danger">Danger</button>

<h1 id="form_elements">Fieldsets, Legends, and Form Elements</h1>
<form class="form">
  <fieldset>
    <legend>Legend</legend>
    <div class="form-group">
      <label for="text_field" class="required">Text Field:</label>
      <input type="text" class="form-control" id="text_field"/>
    </div>
    <div class="form-group">
      <label for="text_area">Text Area:</label>
      <textarea id="text_area" class="form-control"></textarea>
    </div>
    <div class="form-group">
      <label for="select_element">Select Element:</label>
      <select class="form-control" name="select_element">
        <optgroup label="Option Group 1">
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </optgroup>
        <optgroup label="Option Group 2">
          <option value="1">Option 1</option>
          <option value="2">Option 2</option>
          <option value="3">Option 3</option>
        </optgroup>
      </select>
    </div>
    <div class="form-group">
      <label for="radio_buttons">Radio Buttons:</label>

      <div class="radio">
        <label><input type="radio" name="radio_button" value="radio_1"/> Radio 1</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="radio_button" value="radio_2"/> Radio 2</label>
      </div>
      <div class="radio">
        <label><input type="radio" name="radio_button" value="radio_3"/> Radio 3</label>
      </div>
    </div>
    <div>
      <label for="checkboxes">Checkboxes:</label>

      <div class="checkbox">
        <label><input type="checkbox" name="checkboxes" value="check_1"/> Checkbox 1</label>
      </div>
      <div class="checkbox">
        <label><input type="checkbox" name="checkboxes" value="check_2"/> Checkbox 2</label>
      </div>
      <div class="checkbox">
        <label><input type="checkbox" name="checkboxes" value="check_3"/> Checkbox 3</label>
      </div>
    </div>
    <div class="form-group">
      <label for="password">Password:</label>
      <input type="password" class="password" name="password"/>
    </div>
    <div class="form-group">
      <label for="file">File Input:</label>
      <input type="file" class="file" name="file"/>
    </div>
    <div class="actions">
      <input class="btn btn-warning" type="reset" value="Clear"/>
      <input class="btn btn-primary" type="submit" value="Submit"/>
    </div>
  </fieldset>
</form>

<hr/>

<h1 id="tables">Tables</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Table Header 1</th>
    <th>Table Header 2</th>
    <th>Table Header 3</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Division 1</td>
    <td>Division 2</td>
    <td>Division 3</td>
  </tr>
  <tr>
    <td>Division 1</td>
    <td>Division 2</td>
    <td>Division 3</td>
  </tr>
  <tr>
    <td>Division 1</td>
    <td>Division 2</td>
    <td>Division 3</td>
  </tr>
  </tbody>
</table>

<hr/>

<h1 id="misc">Misc Stuff - abbr, acronym, pre, code, sub, sup, etc.</h1>

<p>
  Lorem <sup>superscript</sup> dolor <sub>subscript</sub> amet, consectetuer adipiscing elit. Nullam dignissim
  convallis est. Quisque aliquam. <cite>cite</cite>. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi,
  imperdiet at, tincidunt nec, gravida vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi
  volutpat justo, eu volutpat enim diam eget metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla
  nonummy. <acronym title="National Basketball Association">NBA</acronym> Mauris a ante. Suspendisse quam sem,
  consequat at, commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus. <abbr title="Avenue">AVE</abbr>
</p>

<pre>
  <p>
    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam dignissim convallis est. Quisque aliquam. Donec
    faucibus. Nunc iaculis suscipit dui. Nam sit amet sem. Aliquam libero nisi, imperdiet at, tincidunt nec, gravida
    vehicula, nisl. Praesent mattis, massa quis luctus fermentum, turpis mi volutpat justo, eu volutpat enim diam eget
    metus. Maecenas ornare tortor. Donec sed tellus eget sapien fringilla nonummy.
    <acronym title="National Basketball Association">NBA</acronym> Mauris a ante. Suspendisse quam sem, consequat at,
    commodo vitae, feugiat in, nunc. Morbi imperdiet augue quis tellus. <abbr title="Avenue">AVE</abbr>
  </p>
</pre>

<blockquote>
  "This stylesheet is going to help so freaking much." <br/>-Blockquote
</blockquote>

<hr/>

<h1>Rails styles</h1>
<br/>

<div class="alert alert-danger">
  <p>This is an alert</p>
</div>
<br/>

<div class="alert alert-warning">
  <p>This is a notice</p>
</div>
<br/>

<h2>Optional</h2>
<div class="alert alert-success">
  <p>This is success</p>
</div>
<br/>

<div class="alert alert-info">
  <p>This is info</p>
</div>
<br/>

<div id="error_explanation">
  <h2>Error Title</h2>

  <p>
    Theoretical text.
  </p>
  <ul class="errors">
    <li>Error 1</li>
    <li>Error 2</li>
  </ul>
</div>
<br/>

<!-- End of Sample Content -->

app/views/images/index.html.erb
<table id="images" class="table table-striped">
  <thead>
    <tr>
      <th>Tags</th>
      <th>ID</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @images.each do |image| %>
    <tr data-id="<%= image.id %>">
      <td>
        <ul>
          <% image.tags.each do |tag| %>
            <li><%= tag %></li>
          <% end %>
        </ul>
      </td>
      <td><%= image.id %></td>
      <td class="actions">
        <%= link_to '<span class="glyphicon glyphicon-cloud-upload"><span> Create'.html_safe, new_image_servlet_path(image.id), class: 'btn btn-success create' %>
        <%= link_to '<span class="glyphicon glyphicon-trash"><span> Delete'.html_safe, image_path(image.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger delete' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Port Authority</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!--[if lt IE 9]>
  <p class="browsehappy">
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade</a> to improve your experience.
  </p>
<![endif]-->

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/servlets/index.html.erb
<table id="servlets" class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Image</th>
  </tr>
  </thead>
  <tbody>
  <% @servlets.each do |servlet| %>
    <tr data-id="<%= servlet.id %>">
      <td><%= servlet.name %></td>
      <td><%= servlet.image %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/servlets/new.html.erb
<%= form_for @servlet, html: { role:'form' } do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.select :image, @image.tags.push(@image.id), {}, class: 'form-control' %>
  </div>
  <div class="panel panel-default panel-primary" id="expose_ports">
    <div class="panel-heading">Exposed Ports</div>
    <div class="panel-body">
      <%= f.fields_for :ports do |pf| %>
        <% @image.exposed_ports.each do |p| %>
          <div class="row">
            <%= pf.label p %>
            <%= pf.text_field p %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="panel panel-default panel-primary" id="map_volumes">
    <div class="panel-heading">Map Volumes</div>
    <div class="panel-body">
      <%= f.fields_for :volumes do |vf| %>
        <% @image.volumes.each do |v| %>
          <div class="row">
            <%= vf.label v %>
            <%= vf.text_field v %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= f.submit %>
<% end %>